"""
PDF / plain-text report generator.
───────────────────────────────────
Returns a UTF-8 string that Streamlit can offer as a text download.
For a richer PDF swap in reportlab or fpdf2.
"""

from datetime import datetime


def generate_report(prediction: dict, image_name: str = "uploaded_leaf.jpg") -> str:
    info  = prediction["info"]
    lines = []

    def h1(t): lines.append(f"\n{'='*60}\n  {t}\n{'='*60}")
    def h2(t): lines.append(f"\n{'─'*40}\n  {t}\n{'─'*40}")
    def row(k, v): lines.append(f"  {k:<24}{v}")
    def li(t): lines.append(f"    • {t}")

    lines.append("CropGuard — Plant Disease Detection Report")
    lines.append(f"Generated: {datetime.now().strftime('%A, %d %B %Y  %H:%M')}\n")
    lines.append(f"Image file: {image_name}")

    h1("PRIMARY DIAGNOSIS")
    row("Disease:",       prediction["disease"])
    row("Host plant:",    info["plant"])
    row("Pathogen:",      info["pathogen"])
    row("Severity:",      info["severity"].upper())
    row("Confidence:",    f"{prediction['confidence']*100:.1f}%")
    row("Scan time:",     prediction["timestamp"])

    h2("Description")
    # wrap at ~70 chars
    words = info["description"].split()
    line = "  "
    for w in words:
        if len(line) + len(w) + 1 > 70:
            lines.append(line)
            line = "  " + w + " "
        else:
            line += w + " "
    if line.strip():
        lines.append(line)

    h2("Observed Symptoms")
    for s in info["symptoms"]:
        li(s)

    h2("Recommended Treatment")
    for i, t in enumerate(info["treatment"], 1):
        lines.append(f"    {i}. {t}")

    h2("Prevention Measures")
    for p in info["prevention"]:
        li(p)

    h1("TOP 3 PREDICTIONS")
    for rank, (disease, conf) in enumerate(prediction["top3"], 1):
        lines.append(f"  #{rank}  {disease:<35}  {conf*100:.1f}%")

    h1("DISCLAIMER")
    lines.append(
        "  This report is generated by an AI model and is provided\n"
        "  for informational purposes only. Always consult a certified\n"
        "  agronomist or plant pathologist before applying treatments.\n"
        "  CropGuard accepts no liability for crop management decisions\n"
        "  made on the basis of this report."
    )

    lines.append(f"\n{'─'*60}")
    lines.append("  CropGuard v1.0.0  |  github.com/your-org/cropguard")
    lines.append(f"{'─'*60}\n")

    return "\n".join(lines)
